### ISSUE TITLE
Any textures

### ISSUE THREAD

**Issue by lipki** [SummerFields/Site-Web#10]
I started to fill out an image gallery, in order to reference all textures of SummerFields.
http://ref.summerfields.info/index.php?/category/1

**Comment by tobyplowy** [comment]
@lipki this May be a stupid Question but What what is this for

**Comment by tobyplowy** [comment]
is this a databank for references because it actually is quite useful :D

**Comment by tobyplowy** [comment]
is this a databank for references because it actually is quite useful :D

**Comment by tobyplowy** [comment]
lipki if you need more textures for the gallery i put all the textures we mede here 

stuff by lipki
xdecor
![5d19dd34-2907-11e6-880c-1e4624098e80](https://cloud.githubusercontent.com/assets/16853304/19085331/4bcd62ca-8a6a-11e6-9b9c-a10c869c5bf3.png)
![5d1a839c-2907-11e6-8982-38ec22401577](https://cloud.githubusercontent.com/assets/16853304/19085330/4bcc165e-8a6a-11e6-807c-a4bc61cd6146.png)
![44ac1722-2910-11e6-9699-018130157738](https://cloud.githubusercontent.com/assets/16853304/19085335/4e8df574-8a6a-11e6-8689-f0a413029fe9.png)
![44a72cd0-2910-11e6-8688-e44bbaf93c87](https://cloud.githubusercontent.com/assets/16853304/19085334/4e7f131a-8a6a-11e6-98df-7c52d2948f9e.png)
![d43cbefe-290c-11e6-9e60-53f46128d423](https://cloud.githubusercontent.com/assets/16853304/19085341/546837fc-8a6a-11e6-83dd-9784f8f96349.png)
![8aaddd18-290c-11e6-86bc-6e18657fea83](https://cloud.githubusercontent.com/assets/16853304/19085342/54688fe0-8a6a-11e6-99eb-eccd89111822.png)
![646798f6-290c-11e6-8cdb-6a58b0b35699](https://cloud.githubusercontent.com/assets/16853304/19085353/57ce32e8-8a6a-11e6-9fca-b8f951592f3d.png)
![d7ef1876-290c-11e6-984d-3221a860aba4](https://cloud.githubusercontent.com/assets/16853304/19085352/57cdb502-8a6a-11e6-859a-0b70234fea46.png)
![506bffb2-2912-11e6-8deb-ffdb1b2c3063](https://cloud.githubusercontent.com/assets/16853304/19085361/5affca44-8a6a-11e6-9844-d8ca62e6d994.png)
![503fd770-2912-11e6-937f-0a2bc2d81151](https://cloud.githubusercontent.com/assets/16853304/19085362/5b03e9b2-8a6a-11e6-9d96-1450d8ab2db7.png)
![a290e696-290c-11e6-954f-e122623bb62b](https://cloud.githubusercontent.com/assets/16853304/19085365/5f6a1eae-8a6a-11e6-8c11-eae675471a90.png)
![beba7ae4-290c-11e6-8c24-5d449a1afd6e](https://cloud.githubusercontent.com/assets/16853304/19085366/5f6c093a-8a6a-11e6-8435-9c4ff9f7910d.png)
![fd0204bc-2ccb-11e6-97e9-85fdeb4580e3](https://cloud.githubusercontent.com/assets/16853304/19085368/61f80190-8a6a-11e6-8699-38e3e623c5dc.png)
![fd050c98-2ccb-11e6-8c40-194483ccfa31](https://cloud.githubusercontent.com/assets/16853304/19085369/61f8dffc-8a6a-11e6-8745-d6aa0dedada8.png)
![f1d33d54-2cd0-11e6-93cb-119e5d97550f](https://cloud.githubusercontent.com/assets/16853304/19085372/6591518a-8a6a-11e6-8b9c-3b53e82c62c8.png)
![ead3183e-2cd1-11e6-942e-4a6926b3005a](https://cloud.githubusercontent.com/assets/16853304/19085390/732328a0-8a6a-11e6-88b6-837f1b4539ec.png)
![ee40a1c6-2cd1-11e6-8d4a-d99858466790](https://cloud.githubusercontent.com/assets/16853304/19085396/74bdbff4-8a6a-11e6-87a7-f6d0be9f62ce.png)
![590c4a58-2cd4-11e6-9b22-cbbe6530a3e6](https://cloud.githubusercontent.com/assets/16853304/19085410/7f5cf51a-8a6a-11e6-8765-20dda0ad51b2.png)
![e7889dd6-2914-11e6-8f1e-df5706cbbc28](https://cloud.githubusercontent.com/assets/16853304/19085421/8ab6f6cc-8a6a-11e6-8305-f42f2756424d.png)
![3e7de35e-2ccf-11e6-82bb-258c570ed3e0](https://cloud.githubusercontent.com/assets/16853304/19085428/8cf45efc-8a6a-11e6-8bc4-0c0bd3866588.png)
![c4210bdc-2d22-11e6-93be-0f5551bc75ed](https://cloud.githubusercontent.com/assets/16853304/19085439/98f925a2-8a6a-11e6-87ac-e48a0971fcdd.png)



my stuff
![e339918a-2cd0-11e6-8ee0-c0dc014bc1e0](https://cloud.githubusercontent.com/assets/16853304/19085374/67f40f26-8a6a-11e6-876e-26073ee4c2b6.png)
![wood panel](https://cloud.githubusercontent.com/assets/16853304/19085377/6a3538be-8a6a-11e6-9b14-f133f461f1bd.png)
![e5017432-2ccc-11e6-896f-a8c254e35645](https://cloud.githubusercontent.com/assets/16853304/19085385/70a1526e-8a6a-11e6-9a3b-822298107458.png)
![05514fb6-2cd0-11e6-8745-17c4d5307d41](https://cloud.githubusercontent.com/assets/16853304/19085404/79a41dba-8a6a-11e6-929e-c4641acbc0fa.png)
![a7e018fa-2903-11e6-92f5-68d6e0e3e340](https://cloud.githubusercontent.com/assets/16853304/19085407/7ca63ade-8a6a-11e6-9d93-e09f8e489fe3.png)
![68a2946e-7d4b-11e6-9fcc-490cc31f923c](https://cloud.githubusercontent.com/assets/16853304/19085415/832fa61a-8a6a-11e6-8e05-1f72f06da4ab.png)
![689f7e1e-7d4b-11e6-9dca-4bb30b4f3eca](https://cloud.githubusercontent.com/assets/16853304/19085416/83460e82-8a6a-11e6-9839-a70f873ec186.png)
![68a003d4-7d4b-11e6-8f82-118a7c649f0e](https://cloud.githubusercontent.com/assets/16853304/19085417/834cb390-8a6a-11e6-9880-a1c99ad22872.png)
![5eed9b16-29c3-11e6-8f80-2f759f184502](https://cloud.githubusercontent.com/assets/16853304/19085432/910031e2-8a6a-11e6-8da7-83dccb6ccd48.png)
![carminitegolem](https://cloud.githubusercontent.com/assets/16853304/19085621/39dace08-8a6b-11e6-81f0-d16a313a9320.png)
![helmetcrab](https://cloud.githubusercontent.com/assets/16853304/19085620/39d8527c-8a6b-11e6-87e8-3175d0641e34.png)
![blockgoblin](https://cloud.githubusercontent.com/assets/16853304/19085619/39d83ff8-8a6b-11e6-891c-1705fc0d6da1.png)

**Comment by lipki** [comment]
It's good, I'll add 'em later.
It remains in me still much to add first.

Maybe you can help me, trying to make you an account on the gallery, I'll see if I can get you the rights.

**Comment by tobyplowy** [comment]
@lipki I Will do dat this afternoon :)

**Comment by tobyplowy** [comment]
i made an acount my name is tobyplowy

**Comment by lipki** [comment]
Ok, normally you can add pictures.

Top right, link [Admin]
In admin
left [Plugins]
Below [Take a turn]
On the page [Start of Rondleiding]

---

You can take care of mods.
A new album for each mod.

Then we need to add tags.
dirt, stone, wool, color, glass, mineral, iron, unused ect ...

But we will do so progressively.

thank you very much for you'r help.

**Comment by tobyplowy** [comment]
Is it Good what i did or Should I do it Different?
Also It's no problem I'm happy To help
http://ref.summerfields.info

**Comment by lipki** [comment]
yes ! super.
the tag is good.

**Comment by lipki** [comment]
thank you again!

**Comment by tobyplowy** [comment]
Lipki I think there's something wrong I can't access the website anymore :/

**Comment by tobyplowy** [comment]
I keep getting a page that says Notice: Undefined offset: 5077 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 5613 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 6759 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 6194 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 7332 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 8019 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 9152 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 8262 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 7779 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 9608 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 8706 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 11032 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 11512 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 12457 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 11996 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 12976 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Notice: Undefined offset: 15552 in /srv/data/web/vhosts/ref.summerfields.info/htdocs/include/category_cats.inc.php on line 298

Fatal error: Call to a member function get_size() on null in /srv/data/web/vhosts/ref.summerfields.info/htdocs/themes/modus/themeconf.inc.php on line 266

**Comment by lipki** [comment]
https://framateam.org/signup_user_complete/?id=zdkutw38dbndpdqqznftpxra7r

**Comment by tobyplowy** [comment]
@lipki Sorry I don't know what that website is I don't speak French at all :/ also why can I not access the other website anymore

**Comment by lipki** [comment]
sorry.
I do not know why ref.summefields bug, I perform maintenance on the database, perhaps it's going to walk again.
Retries this, if you please.

The other site framateam, lets discuss in real time, I wanted to discuss with you to resolve the problem.

**Comment by tobyplowy** [comment]
It works agan and it Looks better i Will start work later :D 
Also Can You do The Textures for The lama carpets
https://github.com/SummerFields/SummerFields/issues

**Comment by tobyplowy** [comment]
why are there so many duplicates
![web](https://cloud.githubusercontent.com/assets/16853304/19204878/69947484-8cdf-11e6-86c7-5823c3ab85f6.png)

**Comment by tobyplowy** [comment]
@lipki why are there so many duplicates
![web](https://cloud.githubusercontent.com/assets/16853304/19204897/8a4d2022-8cdf-11e6-893a-2ecda02b3a1e.png)

**Comment by tobyplowy** [comment]
Lipki can you please remove the duplicates so I Can begin adding tags

**Comment by tobyplowy** [comment]
Especially these pages

http://ref.summerfields.info/index.php?/category/626
http://ref.summerfields.info/index.php?/category/619
http://ref.summerfields.info/index.php?/category/620

**Comment by lipki** [comment]
Yes, I do it by hand is long, but I gradually deleted.
You can still put tags on at least one of the images, I would take it into account.
