### ISSUE TITLE
Add new video To video page

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Site-Web#12]
A review video for the minetest edition of summerfields
https://m.youtube.com/watch?v=79w3kKGFu2k
I think it should be added to the video page

**Comment by lipki** [comment]
It is true that I have copy the textures of minecraft into minetest, without seeking to adapt to the specificity of minetest.

**Comment by tobyplowy** [comment]
@lipki The minetest built can be a little bit Different Maybe The wood can be recoloured To look more like minetest wood colors i Can do that If You want

**Comment by tobyplowy** [comment]
@lipki wood baced on original minetest colors NOTE oak is alredy good so i diddent include it
default_acacia_wood
![default_acacia_wood](https://cloud.githubusercontent.com/assets/16853304/20280562/3d959066-aaad-11e6-8a37-8d76c5746b8c.png)
default_aspen_wood
![default_aspen_wood](https://cloud.githubusercontent.com/assets/16853304/20280564/3d95dc92-aaad-11e6-9b5e-3af23ffaf75b.png)
default_junglewood
![default_junglewood](https://cloud.githubusercontent.com/assets/16853304/20280565/3d9a83fa-aaad-11e6-9ba7-6e40e7479f59.png)
default_pine_wood
![default_pine_wood](https://cloud.githubusercontent.com/assets/16853304/20280563/3d960f82-aaad-11e6-9c2e-dc067ca2558e.png)

**Comment by lipki** [comment]
Yep, I agree with that.

**Comment by tobyplowy** [comment]
:D

**Comment by tobyplowy** [comment]
@lipki is this video good to be put on the website?

**Comment by tobyplowy** [comment]
@lipki is this video good to be put on the website?

**Comment by lipki** [comment]
https://github.com/SummerFields/official/wiki/Add-Video-in-page-Videos
