### ISSUE TITLE
 The snowman recovers a face

### ISSUE THREAD

**Issue by lipki** [SummerFields/Site-Web#13]
![screenshot at 2016-11-15 15 23 57](https://cloud.githubusercontent.com/assets/401965/20309571/ca701326-ab48-11e6-94f8-91d516880fa9.png)

**Comment by tobyplowy** [comment]
I don't understand what This Is about is it a problem or is it just something you're pointing out?

**Comment by lipki** [comment]
The pumpkin in nature had no face.
So the snow golem neither.
But with the model system, I was able to correct that.

**Comment by lipki** [comment]
In fact there is nothing to do here this issue.
