### ISSUE TITLE
release 1.11

### ISSUE THREAD

**Issue by lipki** [SummerFields/Site-Web#14]
@tobyplowy 
You can test if you want
https://github.com/SummerFields/SummerFields/releases/tag/mc_1.11

**Comment by tobyplowy** [comment]
@lipki whin Will it be on the website?

**Comment by tobyplowy** [comment]
@lipki The Jack o Lantern doesn't have glowing face Texture

**Comment by tobyplowy** [comment]
Shulker box Shell is not done yet also The heads Look weird in the inventory

**Comment by lipki** [comment]
Jack o Lantern ... random
Shulker box Shell ... shit !
The heads ... bug minecraft 1.11

**Comment by tobyplowy** [comment]
@lipki Will you also do the minetest build

**Comment by lipki** [comment]
@tobyplowy Can you avoid putting messages everywhere.
I see everything you write, if I do not answer, it's because, I do not have time to make a GOOD answer.
answer here -> https://github.com/SummerFields/Minetest/issues/19

**Comment by lipki** [comment]
https://github.com/SummerFields/SummerFields/pull/289
