### ISSUE TITLE
new downloads page consept

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Site-Web#17]
i think it wuld be a good idea to add sub categorys to the download page
it wuld look like this
![naamloos](https://user-images.githubusercontent.com/16853304/33331830-f78a18c2-d462-11e7-82d1-24560759feb4.png)

**Comment by lipki** [comment]
https://summerfields.github.io/official/games.html
done

**Comment by tobyplowy** [comment]
@lipki thank you for adding it :)
