### ISSUE TITLE
change fork me to fork us

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Site-Web#18]
![naamloos](https://user-images.githubusercontent.com/16853304/33331937-3d052504-d463-11e7-91b0-3e7b864b332d.png)
change that to fork us that makes it sound more enviting becouse you are not alone :D

**Comment by lipki** [comment]
"Fork me on GitHub"
it's Summerfields talking, not me :D
I am not forkable.

**Comment by tobyplowy** [comment]
> I am not forkable

it's Summerfields talking, not me :D
ok that was really funny for some reason XD

But I guess it sort of makes sense

**Comment by lipki** [comment]
I'm looking to relocate the site here on github.
https://summerfields.github.io/official/index.html#Home

**Comment by tobyplowy** [comment]
@lipki Woh that looks interesting

But why what's wrong with http://summerfields.info ?

**Comment by lipki** [comment]
you can not write in, easily.

**Comment by tobyplowy** [comment]
@lipki oh I see
