### ISSUE TITLE
Spell fixes

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Site-Web#2]
First of all I want to compliment you for making this awesome website (It looks really good) On [this](http://summerfields.info/?category/Download/Minetest) Page. mod should be changed to (mods) or (Mod support)

**Comment by lipki** [comment]
it's done

**Comment by tobyplowy** [comment]
@lipki wow that was fast (amazing)

**Comment by tobyplowy** [comment]
@lipki I got another one at the black bar on the top it says image and video. It should be images and videos (next to download)

**Comment by lipki** [comment]
I wonder if we should not merge the two.
- Visuals

**Comment by tobyplowy** [comment]
@lipki you mean make videos and images one button?

**Comment by lipki** [comment]
yes

**Comment by tobyplowy** [comment]
@lipki I'm not sure (I don't hate it. don't like it) it's your choice. ( also now that we're on the topic of changing things. can I do a request make the summerfields Banner bigger And centerd

**Comment by tobyplowy** [comment]
@lipki I thought about merging the buttons (images and videos) and I think it will look better.

**Comment by tobyplowy** [comment]
@lipki also you could add a credits tab on the black bar at the top (to honor the people that work on this project) its just an idea ;D

**Comment by lipki** [comment]
We can do a full page for the team. ..

**Comment by tobyplowy** [comment]
@lipki yes!

**Comment by tobyplowy** [comment]
@lipki another spelling fix (download) should be changed to (downloads) because there's more than just one :P

**Comment by lipki** [comment]
We say it's good.

**Comment by tobyplowy** [comment]
i still have a couple fixes

change 
DOWNLOAD
to DOWNLOAD'S
on this page
http://summerfields.info/?tags

change 
VIDEO
to VIDEO'S
on this page
http://summerfields.info/?pages/Video
