### ISSUE TITLE
FAQ is hard to read

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Site-Web#31]
the white text blends in to the light blue too much
![image](https://user-images.githubusercontent.com/16853304/41607803-2b64f418-73e7-11e8-8600-bff7fcfa7f0f.png)

**Comment by tobyplowy** [comment]
i have dyslexia so that may be part of it

**Comment by lipki** [comment]
Yes, the black background has disappeared.

**Comment by lipki** [comment]
done, thanks :D

**Comment by tobyplowy** [comment]
@lipki close?
