### ISSUE TITLE
Add discord link to the site.

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Site-Web#35]
I think it would be a good way to get a bigger community. and it would get more contributors =D
Maybe it can look like this?
![image](https://user-images.githubusercontent.com/16853304/71222524-2b688200-22d1-11ea-8c02-840adacbd846.png)

**Comment by tobyplowy** [comment]
@lipki Ping

**Comment by lipki** [comment]
It's done, good idea.

**Comment by tobyplowy** [comment]
@lipki It's good but "officiel" it's supposed to be official :D 
You misspelled it. (Just change the E in officiel to an A so it's official)

**Comment by lipki** [comment]
:)

**Comment by tobyplowy** [comment]
Can happen =D
