### ISSUE TITLE
Error when downloading 1.14

### ISSUE THREAD

**Issue by OwOV** [SummerFields/Site-Web#37]
When I go to download 1.14 I get a blank page that just says "not found".
The url to the download is 'https://github.com/SummerFields/SummerFields/releases/download/untagged-e9655c5d8763e855dc9a/SummerFields_rp4.zip'
which seems to not exist or be accessible to others.
I'm using firefox btw.

**Comment by lipki** [comment]
@OwOV Thank you very much for warning, it's fixing.
