### ISSUE TITLE
Texture pack customization

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Site-Web#4]
Hey @lipki do you know [this](http://painterlypack.net/customizer.php) site? I was wondering if you could do something similar with the summer fields website? 

http://painterlypack.net/customizer.php

**Comment by lipki** [comment]
Yes I can, I have already started work on something like this, but it is not yet concluded.

**Comment by tobyplowy** [comment]
@lipki you're the best :D does that mean I can begin making custom variation textures for the pack?

**Comment by lipki** [comment]
of course, that's how I started to contribute, creating my own variation pack.

**Comment by tobyplowy** [comment]
@lipki will it work the same way just select what you want and then just click download And the website makes the package for you? bdw i have some new stuff on this [page](https://github.com/SummerFields/Minetest/issues/13) (for xdecore Minetest)

**Comment by lipki** [comment]
It will not be texture by texture, but rather textureS by textureS.

In fact the site before the last updated offer already that, but we choose the mods, no textures.
So it will come.

**Comment by tobyplowy** [comment]
@lipki awesome you're the best

**Comment by lipki** [comment]
One day !
