### ISSUE TITLE
new minetest image

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Site-Web#5]
old image
![minetest_m](https://cloud.githubusercontent.com/assets/16853304/15805189/803f2342-2b22-11e6-8da9-453c24482822.png)

new image
![nice mine test](https://cloud.githubusercontent.com/assets/16853304/15805175/3df0ecaa-2b22-11e6-952f-9889da905c1e.png)

**Comment by tobyplowy** [comment]
@lipki i have a new minetest image

**Comment by lipki** [comment]
ok
